use std::error::Error;

pub fn run_all() -> Result<(), Box<dyn Error>> {
    Ok(())
}
